version: '3'
services:
  spring-boot-app:
    image: ems-backend-image
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    links:
      - mysql-db

  mysql-db:
    image: mydb-mysql-image
    ports:
      - "3306:3306"
